variables:
  PC_DOC_CHECK: "on"
  PC_PACKAGE_DEPS: libamxc libamxd libamxp libamxb libamxo libamxm libamxj sah-lib-sahtrace-dev libyajl-dev libnetmodel
  BUILD_TARGET: wan-manager

include:
  - remote: 'https://gitlab.com/soft.at.home/ci/gitlab-ci/raw/main/ambiorix-default-pipeline.yml'
